version: '3.8'

services:
  backend:
    build:
      context: ./PixelPower/PixelPower
    container_name: pixelpower-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/PixelPower
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    networks:
      - app-network

  frontend:
    build:
      context: ./PixelPower/PixelPowerFront
    container_name: pixelpower-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: pixelpower-db
    restart: always
    environment:
      POSTGRES_DB: PixelPower
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
