name: CI/CD Pipeline
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build Backend
        run: |
          cd PixelPower/PixelPower
          mvn clean package -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update Angular Budget
        run: |
          cd PixelPower/PixelPowerFront
          if [ -f "angular.json" ]; then
            # Increase component style budget to 40kb
            sed -i 's/"maximumError": "8kb"/"maximumError": "40kb"/g' angular.json
          fi

      - name: Build Frontend
        run: |
          cd PixelPower/PixelPowerFront
          npm install
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create docker-compose.override.yml for image names
        run: |
          cat > docker-compose.override.yml << EOF
          version: '3.8'
          
          services:
            backend:
              image: ${{ secrets.DOCKER_USERNAME }}/pixelpower-backend:latest
          
            frontend:
              image: ${{ secrets.DOCKER_USERNAME }}/pixelpower-frontend:latest
          EOF

      - name: Build and Push Docker Images
        run: |
          docker compose build backend frontend
          docker compose push backend frontend