name: CI/CD Pipeline
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build Backend
        run: |
          cd PixelPower/PixelPower
          mvn clean package 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Frontend
        run: |
          cd PixelPower/PixelPowerFront
          npm install
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Update docker-compose.yml for Docker Hub
        run: |
          # Add image names to your docker-compose file
          sed -i 's/build:/build:\n      image: ${{ secrets.DOCKER_USERNAME }}\/pixelpower-backend:latest/g' docker-compose.yml
          sed -i 's/context: \.\/PixelPower\/PixelPowerFront/context: \.\/PixelPower\/PixelPowerFront\n      image: ${{ secrets.DOCKER_USERNAME }}\/pixelpower-frontend:latest/g' docker-compose.yml

      - name: Build and Push Docker Images
        run: |
          docker compose build backend frontend
          docker compose push backend frontend